### ISSUE TITLE
Create PDF style for RSD

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rsd-style#2]
@pierrefortier we have a rather urgent need (as in few days) for the PDF style of the RSD document. It needs to be pretty as it is being used for a client proposal. Would you have time to make something beautiful? Thanks 😉

**Comment by pierrefortier** [comment]
Sure thing! I'll have it done over the weekend.

**Comment by pierrefortier** [comment]
I just updated with print to pdf output. Here's an example of that output:

[rsd-operator-guidelines.pdf](https://github.com/riboseinc/rsd-style/files/2173907/rsd-operator-guidelines.pdf)

**Comment by ronaldtse** [comment]
@pierrefortier this cover page works!

Minor nits:

* it seems that the section headers are too large in font size (and don't have enough margin when split into two lines)
* the "Note to entry" has too much padding at top/bottom/sides.
* the ToC has too much spacing per-line.
* basically, since this will be a client proposal, we want to fit as much content as we can per page (but without feeling cramped)

Thanks!

**Comment by pierrefortier** [comment]
Sure thing! I've made some updates to address these issues. :)

**Comment by opoudjis** [comment]
i have worked off the stylesheet in the v2.zip from https://github.com/riboseinc/asciidoctor-rsd/issues/5, but that turns out to be the same as v3.zip apart from the copyright resizing.

@pierrefortier I'm not sure whether Ronald's concerns have been addressed in this version or not. There is a wedge of blue on the front page, and the copyright notice is imperfectly hidden on the second page. (The source HTML output is attached to https://github.com/riboseinc/asciidoctor-rsd/issues/5). Could you please try to replicate the error, and eliminate at least the copyright notice by suppressing display?

[rfc6350.pdf](https://github.com/riboseinc/rsd-style/files/2176066/rfc6350.pdf)

**Comment by ronaldtse** [comment]
As @opoudjis mentioned, @pierrefortier, in the PDF there are these issues:

1. half-hidden copyright notice
2. blue wedge on the front page

Could we get them fixed? Thanks!

**Comment by pierrefortier** [comment]
@opoudjis I was not able to replicate the blue wedge. I also can't readily explain why the copyright is misbehaving. I've suppressed it for now as you've suggested. Here is the HTML you shared at https://github.com/riboseinc/asciidoctor-rsd/issues/5 with the slight adjustments:

[rfc6350.html.zip](https://github.com/riboseinc/rsd-style/files/2178362/rfc6350.html.zip)

For reference, here is the PDF output I get with it:

[rfc6350.pdf](https://github.com/riboseinc/rsd-style/files/2178364/rfc6350.pdf)

**Comment by opoudjis** [comment]
Copyright has gone after realising your modification. Blue wedge persists. I'll try to get rid of it myself.

**Comment by opoudjis** [comment]
I have; simple disabling of the wedge section.

[rfc6350.pdf](https://github.com/riboseinc/rsd-style/files/2179820/rfc6350.pdf)
